export const TOP_RIGHT_BUTTON_MARGIN_TOP = 20
export const BOTTOM_ACTION_BAR_HEIGHT = 56
export const BOTTOM_RIGHT_BUTTON_MARGIN_BOTTOM = 28
export const RIGHT_BUTTON_MARGIN_RIGHT = 12
export const MODAL_WIDE_WIDTH = '90%'
export const MODAL_MIDDLE_WIDTH = '70%'
export const MODAL_NARROW_WIDTH = '60%'
